version: '3.8'

networks:
  kinance-net:

services:
  kinance_db:
    container_name: kinancedb
    image: postgres:15
    environment:
      POSTGRES_DB: finfam
      POSTGRES_USER: finfam
      POSTGRES_PASSWORD: finfam123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kinance-net

  kinance_redis:
    container_name: kinance_redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - kinance-net

  kinance_api:
    container_name: kinance_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - kinance_db
      - kinance_redis
    environment:
      DB_HOST: kinance_db
      DB_USER: finfam
      DB_PASSWORD: finfam123
      DB_NAME: finfam
      REDIS_HOST: kinance_redis
      JWT_SECRET: your-super-secret-jwt-key
    networks:
      - kinance-net

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  
  ngrok:
      image: ngrok/ngrok:latest
      container_name: ngrok
      restart: unless-stopped
      command:
        - "start"
        - "--all"
        - "--config"
        - "/etc/ngrok.yml"
      volumes:
        - ./ngrok.yml:/etc/ngrok.yml
      environment:
        - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
        - NGROK_CONFIG=/etc/ngrok.yml
      ports:
        - 4040:4040

volumes:
  postgres_data:
  redis_data: